{
 "title": "spam2000",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Top 5 users by order quantity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (email) (ordered_histogram_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of orders in the last 5 min",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(ordered_histogram_count) - sum(ordered_histogram_count offset 5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Employee info",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (email,exported_job) (name_gauge)"
    }
   ]
  },
  {
   "title": "Average order processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(ordered_histogram_sum) / 1000 / sum(ordered_histogram_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}